#! /bin/sh

if [ -n $(which fpclean) ]; then
	fpclean $*;
else
# fpclean wraps fpc and filter its output to make it more useful.
fpc $*  2>&1 |

# Translate file addresses to a more familiar format...
# For line only
sed -r 's/' |
# For line + character offset
sed -r 's//\1:\2:\3/' |

# Remove the spurious ld warning
grep -v ''

exit ${PIPESTATUS[0]}
fi
